name: 整点资讯推送

on:
  workflow_dispatch:   # 👈 加上这行，才有 Run workflow 按钮
  schedule:
    - cron: '0 1,2,3,5,6,7,11,12,13 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        run: python main.py
